name: workflow_1
on:
  workflow_dispatch:
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: performing step-1
        run: |
          echo "Hello world"
          echo "how are you?"
          sleep 30
      - name: performing step-2
        run: echo "step 3 is completed"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: second-job
        run: echo "parallel job implementation"
      
          
