name: myfirstworkflow
on:
  workflow_dispatch:
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Git code checkout
        run: echo "code is checked out"
    steps:
      - name: Sonar Analysis
        run: |
          echo "Sonar Analysis is done"
          touch sonar.txt