name: schedule-workflow
on:
  schedule:
    - cron: '*/2 * * * *'  
jobs:
  schedule-job:
    runs-on: ubuntu-22.04
    steps:
      - name: step-a
        run: echo "This is a schedule job"
        
